### ISSUE TITLE
Can not unzip archive with pre-trained models

### ISSUE THREAD

**Issue by aduzhinskaya** [LARC-CMU-SMU/FoodSeg103-Benchmark-v1#16]
Hello,

I downloaded the archive from the [sharepoint link](https://smu-my.sharepoint.com/personal/xwwu_smu_edu_sg/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fxwwu%5Fsmu%5Fedu%5Fsg%2FDocuments%2Fcheckpoints%2Ezip&parent=%2Fpersonal%2Fxwwu%5Fsmu%5Fedu%5Fsg%2FDocuments) but, unfortunately, I was getting the following error when I tried to unzip it.

```
$ unzip ./checkpoints.zip
error [./checkpoints.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```

Could you please check that the archive was properly zipped? 

Thank you very much!!

**Comment by XiongweiWu** [comment]
@aduzhinskaya It's a bit strange since other researchers do not report this issue. But never mind, let me check soon and I will update you when I finish.

**Comment by XiongweiWu** [comment]
@aduzhinskaya Hi, I have decompressed the file in Macbook and Win10 machine without any issue. I guess the issue is that the uploaded zip file is not in .zip archive format (I compress it in Win10 machine directly), and you may use the method reported here to resolve it: https://askubuntu.com/questions/54904/unzip-error-end-of-central-directory-signature-not-found, or directly unzip it in Win10/Macbook and transfer the weights in your server.

**Comment by aduzhinskaya** [comment]
Thank you, changing the unzipping tool resolved the issue.
